# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
      
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: pass, roles: 'ROLE_ADMIN' }
                  
    firewalls:
        login:
            pattern:    ^/admin/login$
            security: false
            
        secured_area:
            form_login:
                check_path: /admin/login_check  
                login_path: /admin/login     
                
            logout:
                path:   /admin/logout
                target: /admin/
    
            http_basic:
                realm: "Secured Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    

   